name: lunosprite
version: '1.0+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Animated sprite editor & pixel art tool
description: |
  LunoSprite is a free and open source program to create animated sprites.
  It is a fork of the last GPLv2 commit of Aseprite.
icon: prime/share/aseprite/data/icons/ase48.png

grade: stable
confinement: strict

apps:
  lunosprite:
    command: bin/aseprite
    desktop: src/desktop/lunosprite.desktop
    plugs:
      - home
      - unity7
      - x11

parts:
  lunosprite:
    source: https://github.com/LunoSprite/LunoSprite.git
    plugin: cmake
    build-packages:
      - build-essential
      - libx11-dev
      - libxcursor-dev
      - ninja-build
    stage-packages:
      - libx11-6
      - libxrender1
      - libxfixes3
      - libxcursor1
    override-stage: |
      snapcraftctl stage
      # Copy the .desktop over.
      mkdir -p "${SNAPCRAFT_PRIME}/src/desktop/"
      cp "${SNAPCRAFT_PART_SRC}/desktop/lunosprite.desktop" "${SNAPCRAFT_PRIME}/src/desktop/"
      sed -i 's|Icon=lunosprite|Icon=icon|' "${SNAPCRAFT_PRIME}/src/desktop/lunosprite.desktop"
