name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup SDK
      uses: android-actions/setup-android@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libcurl4-gnutls-dev libfreetype6-dev libgif-dev libjpeg-dev libpixman-1-dev libpng-dev libsdl2-dev libsdl2-image-dev libtinyxml2-dev libx11-dev libxcursor-dev ninja-build zlib1g-dev libarchive-dev

    - name: Configure CMake project
      run: |
        cmake -S . -B build -G Ninja -DGEN_ONLY=ON

    - name: Build project
      run: cmake --build build

    - name: Setup Submodule
      run: git clone https://github.com/LibreSprite/ls-android-deps.git android

    - name: Build Android App
      run: |
        cd android
        sh ./gradlew --no-daemon --parallel build

    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: libresprite-development-android
        path: android/app/build/outputs/apk/all_in_one/debug/app-all_in_one-debug.apk
